### ISSUE TITLE
Is hin2vec suitable for directed network?

### ISSUE THREAD

**Issue by zuozijiZHOULI** [csiesheep/hin2vec#7]

**Comment by csiesheep** [comment]
Hi, sorry for the late reply and thanks for the asking.
Yes, hin2vec works on directed networks if you define two direction edges for nodes.

E.g., Amy(User) ---> Bob(User).      "--->" means following

In edge list file:
Amy   User   Bob   User   U->U                 #U->U means following
...
Bob    User   Amy   User  U<-U                 #U<-U means being followed

**Comment by zuozijiZHOULI** [comment]
Thank you for your help ! I have another question that I don't quite understand, why is it that when U-U is represented as a vector,U-U,U-U is represented as a vector?

**Comment by csiesheep** [comment]
Hi, I am sorry that I do not quite understand your question. Could you describe more? Thanks!

**Comment by zuozijiZHOULI** [comment]
Hi,thank you for your reply.I am so sorry,My English is not good, I will try my best to show my problem. I've run the code of HIN2VEC, but I don't really understand about metapath2vec. The "u-u" relationship is already represented as a vector, why would you want to represent "u-u, u-u" as a vector?I'm confused about what "u-u, u-u" stands for.Why is the representation of relationships not the representation of a single relationship, but rather the representation of multiple relationships after iteration?Could you please tell me in detail or provide me with more materials about the experiment? If you can help me, I will be very grateful.

**Comment by csiesheep** [comment]
Hi! Thanks for elaborating. It is because that each metapath has its own semantic meaning. In the example you mentioned, "U-U" means direct friendship and "U-U,U-U" ("U-U-U for short") means co-friendship. There are more relationships that can be modeled as multiple-hop metapaths, such as "Author-Paper-Author" means co-authorship and "Author-Paper-Conference-Paper-Author" means two authors have publications in the same conference. Only consider one hop relationships between nodes is not enough. My experiments show that considering 3-hop or 4-hop metapaths really help the performance of applications.

**Comment by zuozijiZHOULI** [comment]
Thank you for your serious reply. I have understood.Wish you a happy life!
